### PR TITLE
Add relevent content function

### PR DESCRIPTION
**Pull request by Shibi-bala**
Found that most of the relevant page data was stored in <div class="body"> for the mongodb website. I added a function to extract all html elements under that div to be processed by the html to text conversion. Hopefully it makes the documents more relevant to what the actual page content is.

[withContentExtraction.txt](https://github.com/mongodben/atlas-static-site-search/files/9142576/withContentExtraction.txt)
[withoutContentExtraction.txt](https://github.com/mongodben/atlas-static-site-search/files/9142577/withoutContentExtraction.txt)

### CODE REVIEW

**Review by mongodben — COMMENTED** [review]
i think we need to rethink the approach here. this approach will work for mongodb docs sites, which use the `.body` class to connote the documentation text. however, this isn't generalizable to all static sites. 

to make the parsing generalizable to *all* HTML pages, we should strip out certain semantic HTML elements that won't be part of the page contents, such as `<header>`/`<footer>`/`<nav>`.

if you want to do something specific for mongodb docs sites (which i think is fine), then it's worth explicitly calling out in a conditional. for ex in the `writePageContents` function:

```js
if(fullDocument.loc.startsWith("https://www.mongodb.com/docs/")) {
// only pull out the .body element
}
```

also i think this logic should be part of the [html2text lambda function endpoint](https://github.com/mongodben/atlas-static-site-search/blob/main/skunkworks-atlas-docs-search/handler.js) that nick added yesterday, so all parsing logic is located within that one place.

**Review by nlarew — APPROVED** [review]
LGTM!

**Review by mongodben — APPROVED** [review]
lgtm from me as well!

**Comment by mongodben** [comment]
@nlarew i've merged changes, can you deploy?

**Comment by nlarew** [comment]
Deployed!

**Pull request merged**
